switch to static dispatch while keeping improved compile times!
Historical note: I just added `'static` becasue the compiler suggested it.

```
error[E0310]: the parameter type `S` may not live long enough
   --> libs\web\src\lib.rs:374:13
    |
360 | fn emulate_for_a_single_frame<S: State>(pinky: Rc<RefCell<PinkyWeb<S>>>) {
    |                               -- help: consider adding an explicit lifetime bound `S: 'static`...
...
374 |             web::set_timeout( move || { emulate_for_a_single_frame( pinky ); }, 0 );
    |             ^^^^^^^^^^^^^^^^
    |
note: ...so that the type `[closure@libs\web\src\lib.rs:374:31: 374:79 pinky:std::rc::Rc<std::cell::RefCell<PinkyWeb<S>>>]` will meet its required lifetime bounds
   --> libs\web\src\lib.rs:374:13
    |
374 |             web::set_timeout( move || { emulate_for_a_single_frame( pinky ); }, 0 );
    |             ^^^^^^^^^^^^^^^^
```